/*Esto son los drops de las tablas*/
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;
DROP TABLE JUEGOS CASCADE CONSTRAINTS;
DROP TABLE COMPETICIONES CASCADE CONSTRAINTS;
DROP TABLE JORNADAS CASCADE CONSTRAINTS;
DROP TABLE ENFRENTAMIENTOS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE PATROCINADORES CASCADE CONSTRAINTS;
DROP TABLE PATROCINADORES_EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE EQUIPO_COMPETICION CASCADE CONSTRAINTS;
/*Fin de los drop de las tablas*/

/*Creacion de las tablas*/
CREATE TABLE EQUIPOS (
    COD_EQUIPO NUMBER(5) 
        GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    NOMBRE VARCHAR2 (50) NOT NULL,
    FECHA_FUNDACION DATE NOT NULL
);
CREATE TABLE JUGADORES(
    COD_JUGADOR NUMBER(5)GENERATED ALWAYS AS IDENTITY(START WITH 1)PRIMARY KEY,
    NOMBRE_JUGADOR VARCHAR2 (50) NOT NULL,
    NACIONALIDAD VARCHAR2(50) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    NICKNAME VARCHAR2(20) NOT NULL,
    ROL VARCHAR2(10) NOT NULL,
    SUELDO NUMBER(7) NOT NULL,
    COD_EQUIPO NUMBER(5)
);
CREATE TABLE STAFF(
    COD_STAFF NUMBER(5) GENERATED ALWAYS AS IDENTITY(START WITH 1)PRIMARY KEY,
    NOMBRE VARCHAR2 (50) NOT NULL,
    CARGO VARCHAR2(50) NOT NULL,
    SUELDO FLOAT(7)NOT NULL,
    COD_EQUIPO NUMBER(5)

);
CREATE TABLE COMPETICIONES (
    COD_COMPE NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    NOMBRE VARCHAR2 (50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    CURSO NUMBER(1) NOT NULL,
    EQUIPO_GANADOR NUMBER(5),
    COD_JUEGO NUMBER(5) NOT NULL
);
CREATE TABLE JUEGOS(
    COD_JUEGO NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    NOMBRE VARCHAR2 (50) NOT NULL,
    DESARROLLADORA VARCHAR2 (50) NOT NULL,
    FECHA_LANZAMIENTO DATE NOT NULL
);
CREATE TABLE JORNADAS (
    COD_JORNADAS NUMBER(5)
        GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    NUM_JORNADA NUMBER(3) NOT NULL,
    DIA DATE NOT NULL,
    COD_COMPE NUMBER(5) NOT NULL
);
CREATE TABLE ENFRENTAMIENTOS(
    COD_ENFRENTAMIENTO NUMBER(5) 
        GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    FECHA DATE NOT NULL,
    COD_JORNADA NUMBER(5) NOT NULL,
    HORA VARCHAR2(5) NOT NULL,
    RESULTADO VARCHAR2(30),
    COD_EQUIPO_LOCAL NUMBER(5) NOT NULL,
    COD_EQUIPO_VISITANTE NUMBER(5) NOT NULL
);
CREATE TABLE USUARIOS (
    COD_USUARIO NUMBER(3)
        GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    TIPO VARCHAR2(20) NOT NULL,
    CONTRASEÑA VARCHAR2(50) NOT NULL
);
CREATE TABLE PATROCINADORES(
    COD_PATROCINADORES NUMBER(5)GENERATED ALWAYS AS IDENTITY (START WITH 1)
                                                              PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);
CREATE TABLE PATROCINADORES_EQUIPOS(
    COD_PATR_EQUI NUMBER(5)GENERATED ALWAYS AS IDENTITY(START WITH 1)
                                                        PRIMARY KEY,
    COD_PATROCINADORES NUMBER(5) NOT NULL,
    COD_EQUIPO NUMBER(5) NOT NULL
);
CREATE TABLE EQUIPO_COMPETICION(
    COD_EQUIPO_COMPE NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1) 
                                                            PRIMARY KEY,
    COD_EQUIPO NUMBER(5) NOT NULL,
    COD_COMPETICION NUMBER(5) NOT NULL,
    PUNTOS NUMBER(3) NOT NULL
);

 /*Fin de creacion de tablas*/


/*Comenzamos con las claves foraneas*/
ALTER TABLE JUGADORES 
ADD CONSTRAINT FK_EQUIPO_EN_JUGADOR 
FOREIGN KEY (COD_EQUIPO) 
REFERENCES EQUIPOS (COD_EQUIPO);

ALTER TABLE ENFRENTAMIENTOS
ADD CONSTRAINT FK_JORNADA
FOREIGN KEY (COD_JORNADA)
REFERENCES JORNADAS(COD_JORNADAS);

ALTER TABLE STAFF 
ADD CONSTRAINT FK_EQUIPO_EN_STAFF
FOREIGN KEY (COD_EQUIPO)
REFERENCES EQUIPOS (COD_EQUIPO);

ALTER TABLE COMPETICIONES 
ADD CONSTRAINT FK_JUEGO_EN_COMPE
FOREIGN KEY (COD_JUEGO)
REFERENCES JUEGOS(COD_JUEGO); 

ALTER TABLE JORNADAS
ADD CONSTRAINT FK_COMPETICION_EN_JORNADA
FOREIGN KEY (COD_COMPE)
REFERENCES COMPETICIONES(COD_COMPE);  

ALTER TABLE ENFRENTAMIENTOS
ADD CONSTRAINT FK_EQUIPO_LOCAL
FOREIGN KEY (COD_EQUIPO_LOCAL)
REFERENCES EQUIPOS(COD_EQUIPO); 

ALTER TABLE ENFRENTAMIENTOS
ADD CONSTRAINT FK_EQUIPO_VISITANTE
FOREIGN KEY (COD_EQUIPO_VISITANTE)
REFERENCES EQUIPOS(COD_EQUIPO); 

ALTER TABLE PATROCINADORES_EQUIPOS
ADD CONSTRAINT FK_PATRO_EN_PATRO_EQUIPOS
FOREIGN KEY (COD_PATROCINADORES) 
REFERENCES PATROCINADORES(COD_PATROCINADORES);

ALTER TABLE PATROCINADORES_EQUIPOS
ADD CONSTRAINT FK_EQUIPOS_EN_PATRO_EQUIPOS
FOREIGN KEY (COD_EQUIPO) 
REFERENCES EQUIPOS(COD_EQUIPO);

ALTER TABLE EQUIPO_COMPETICION
ADD CONSTRAINT FK_EQUIPO_EQUIPO_COMPE
FOREIGN KEY (COD_EQUIPO)
REFERENCES EQUIPOS(COD_EQUIPO);

ALTER TABLE EQUIPO_COMPETICION
ADD CONSTRAINT FK_COMPE_EQUIPO_COMPE
FOREIGN KEY (COD_COMPETICION)
REFERENCES COMPETICIONES(COD_COMPE);
/*Fin de las claves foraneas*/

/*Comenzamos con los check*/
ALTER TABLE JUGADORES
ADD CONSTRAINT CHCK_SUELDO_JUGADORES
CHECK (SUELDO>1323)
;

ALTER TABLE STAFF
ADD CONSTRAINT CHCK_CARGO_STAFF
CHECK (CARGO IN('Asistente','Entrenador'))
;

ALTER TABLE STAFF
ADD CONSTRAINT CHCK_SUELDO_STAFF
CHECK (SUELDO>1323)
;

ALTER TABLE COMPETICIONES
ADD CONSTRAINT CHCK_CURSO_COMPE
CHECK (CURSO IN(0,1))
;

ALTER TABLE USUARIOS
ADD CONSTRAINT CHCK_TIPO_USU
CHECK (TIPO IN('Administrador','Usuario'))
;
/*Fin de los check*/


/*Creacion de las vistas*/
/*Para hacer la consulta de quienes son los juegadores de cada equipo equipo*/
CREATE OR REPLACE VIEW JUGADORES_EQUIPO AS
SELECT J.NOMBRE_JUGADOR, J.NACIONALIDAD, J.ROL, J.SUELDO, E.NOMBRE "EQUIPO" 
FROM JUGADORES J
JOIN EQUIPOS E
ON E.COD_EQUIPO=J.COD_EQUIPO ORDER BY E.COD_EQUIPO;
/*Consulta para saber que tipos de torneos pueden existir y sus fechas de 
inicio y fin*/
CREATE OR REPLACE VIEW JUEGOS_COMPE AS
SELECT J.COD_JUEGO, J.NOMBRE"JUEGO", C.NOMBRE, C.FECHA_INICIO, C.FECHA_FIN 
FROM JUEGOS J 
JOIN COMPETICIONES C 
ON J.COD_JUEGO = C.COD_JUEGO;
/*Los equipos y que competiciones juegan*/
CREATE OR REPLACE VIEW EQUIPOS_COMPE AS
SELECT E.COD_EQUIPO, E.NOMBRE AS NOMBRE_EQUIPO, C.COD_COMPE, 
C.NOMBRE AS NOMBRE_COMPETICION, C.COD_JUEGO, J.NOMBRE AS NOMBRE_JUEGO
FROM EQUIPOS E
JOIN EQUIPO_COMPETICION EC ON E.COD_EQUIPO = EC.COD_EQUIPO
JOIN COMPETICIONES C ON C.COD_COMPE = EC.COD_COMPETICION
JOIN JUEGOS J ON J.COD_JUEGO = C.COD_JUEGO
ORDER BY E.NOMBRE;