SET SERVEROUTPUT ON;
/*PAQUETE CRUD STAFF*/
/*SE USARA EN JAVA EN LAS VENTANAS DEDICADAS AL CRUD DE STAFF*/
CREATE OR REPLACE PACKAGE GESTION_STAFF AS
-- AGREGAR STAFF
    PROCEDURE AGREGAR_STAFF (
       V_NOMBRE VARCHAR2,
       V_CARGO VARCHAR2,
       V_SUELDO NUMBER,
       V_COD_EQUIPO NUMBER);
    
-- ELIMINAR STAFF
    PROCEDURE ELIMINAR_STAFF (V_COD_STAFF NUMBER);
    
-- ACTUALIZAR STAFF
    PROCEDURE ACTUALIZAR_STAFF (
        V_COD_STAFF NUMBER,
        V_NOMBRE VARCHAR2,
        V_CARGO VARCHAR2,
        V_SUELDO NUMBER);
        
END GESTION_STAFF;
/


CREATE OR REPLACE PACKAGE BODY GESTION_STAFF AS
-- AGREGAR STAFF
    PROCEDURE AGREGAR_STAFF (
       V_NOMBRE VARCHAR2,
       V_CARGO VARCHAR2,
       V_SUELDO NUMBER,
       V_COD_EQUIPO NUMBER) IS
    BEGIN
        INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO)
        VALUES (V_NOMBRE,V_CARGO,V_SUELDO,V_COD_EQUIPO);
        DBMS_OUTPUT.PUT_LINE ('STAFF INSERTADO CON EXITO');
    END AGREGAR_STAFF;
    
-- ELIMINAR STAFF
    PROCEDURE ELIMINAR_STAFF (
    V_COD_STAFF NUMBER) IS
    BEGIN
        DELETE FROM STAFF WHERE COD_STAFF = V_COD_STAFF;
        DBMS_OUTPUT.PUT_LINE('STAFF ELIMINADO CON EXITO');
    END ELIMINAR_STAFF;
    
-- ACTUALIZAR STAFF
    PROCEDURE ACTUALIZAR_STAFF (
       V_COD_STAFF NUMBER,
       V_NOMBRE VARCHAR2,
       V_CARGO VARCHAR2,
       V_SUELDO NUMBER) IS
    BEGIN
        UPDATE STAFF SET
        NOMBRE = V_NOMBRE,
        CARGO = V_CARGO,
        SUELDO = V_SUELDO
        WHERE COD_STAFF = V_COD_STAFF;
        DBMS_OUTPUT.PUT_LINE('STAFF ACTUALIZADO CON EXITO');
    END ACTUALIZAR_STAFF;
END GESTION_STAFF;
        