SET SERVEROUTPUT ON;
/*Procedimientos*/
/*Sacamos por pantalla el nombre del juego, cuando empieza y acaba, 
nombre de equipo, nombre del staff y cantidad de jugadores */
CREATE OR REPLACE PROCEDURE OBTENER_INFO_COMPETICION(
    FECHA_CONSULTA IN DATE
) 
AS
    CURSOR_INFO_COMPETICION SYS_REFCURSOR;
    NOMBRE_JUEGO JUEGOS.NOMBRE%TYPE;
    FECHA_INICIO COMPETICIONES.FECHA_INICIO%TYPE;
    FECHA_FIN COMPETICIONES.FECHA_FIN%TYPE;
    NOMBRE_EQUIPO EQUIPOS.NOMBRE%TYPE;
    NOMBRE_STAFF STAFF.NOMBRE%TYPE;
    CANTIDAD_JUGADORES NUMBER;
BEGIN
    OPEN CURSOR_INFO_COMPETICION FOR
    SELECT J.NOMBRE AS NOMBRE_JUEGO,
           C.FECHA_INICIO,
           C.FECHA_FIN,
           E.NOMBRE AS NOMBRE_EQUIPO,
           S.NOMBRE AS NOMBRE_STAFF,
           COUNT(DISTINCT JUG.COD_JUGADOR) AS CANTIDAD_JUGADORES
    FROM COMPETICIONES C
    JOIN JUEGOS J ON C.COD_JUEGO = J.COD_JUEGO
    JOIN EQUIPO_COMPETICION EC ON C.COD_COMPE = EC.COD_COMPETICION
    JOIN EQUIPOS E ON EC.COD_EQUIPO = E.COD_EQUIPO
    LEFT JOIN JUGADORES JUG ON E.COD_EQUIPO = JUG.COD_EQUIPO
    LEFT JOIN STAFF S ON E.COD_EQUIPO = S.COD_EQUIPO
    WHERE FECHA_CONSULTA BETWEEN C.FECHA_INICIO AND C.FECHA_FIN
    GROUP BY J.NOMBRE, C.FECHA_INICIO, C.FECHA_FIN, E.NOMBRE, S.NOMBRE;

    DBMS_OUTPUT.PUT_LINE('Información de la competición:');
    LOOP
        FETCH CURSOR_INFO_COMPETICION INTO NOMBRE_JUEGO, FECHA_INICIO,
        FECHA_FIN, NOMBRE_EQUIPO, NOMBRE_STAFF, CANTIDAD_JUGADORES;
        EXIT WHEN CURSOR_INFO_COMPETICION%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Juego: ' || NOMBRE_JUEGO);
        DBMS_OUTPUT.PUT_LINE('Fecha de inicio: ' || 
        TO_CHAR(FECHA_INICIO, 'dd/MM/yyyy'));
        DBMS_OUTPUT.PUT_LINE('Fecha de fin: ' || 
        TO_CHAR(FECHA_FIN, 'dd/MM/yyyy'));
        DBMS_OUTPUT.PUT_LINE('Equipo: ' || NOMBRE_EQUIPO);
        DBMS_OUTPUT.PUT_LINE('Miembro del staff: ' || NOMBRE_STAFF);
        DBMS_OUTPUT.PUT_LINE('Cantidad de jugadores: ' || CANTIDAD_JUGADORES);
        DBMS_OUTPUT.PUT_LINE('-----------------------');
    END LOOP;

    CLOSE CURSOR_INFO_COMPETICION;
END;
/
BEGIN
    OBTENER_INFO_COMPETICION (TO_DATE('25/04/2020','dd/MM/yyyy'));
END;
/
/*Sacamos por pantalla informacion sobre los juegadores, lo usaremos
en el crud de jugadores*/
CREATE OR REPLACE PROCEDURE INFO_GENERAL (
    EQUIPO EQUIPOS.NOMBRE%TYPE
)
AS
    CURSOR_EQUIPO SYS_REFCURSOR;
    ENOMBRE EQUIPOS.NOMBRE%TYPE;
    JNOMBRE JUGADORES.NOMBRE_JUGADOR%TYPE;
    JNACIONALIDAD JUGADORES.NACIONALIDAD%TYPE;
    JNICKNAME JUGADORES.NICKNAME%TYPE;
    JROL JUGADORES.ROL%TYPE;
    CNOMBRE COMPETICIONES.NOMBRE%TYPE;
BEGIN
    OPEN CURSOR_EQUIPO FOR
SELECT E.NOMBRE, J.NOMBRE_JUGADOR, J.NACIONALIDAD, J.NICKNAME, J.ROL, 
       C.NOMBRE
FROM JUGADORES J
JOIN EQUIPOS E ON J.COD_EQUIPO = E.COD_EQUIPO
JOIN STAFF S ON J.COD_EQUIPO = S.COD_EQUIPO
JOIN EQUIPO_COMPETICION EC ON E.COD_EQUIPO = EC.COD_EQUIPO
JOIN COMPETICIONES C ON EC.COD_COMPETICION = C.COD_COMPE
WHERE E.NOMBRE = EQUIPO
ORDER BY E.NOMBRE;

DBMS_OUTPUT.PUT_LINE('Esta es la informacion');
DBMS_OUTPUT.PUT_LINE('-----------------------');


LOOP 
FETCH CURSOR_EQUIPO INTO ENOMBRE,JNOMBRE,JNACIONALIDAD,JNICKNAME,JROL,CNOMBRE;
        EXIT WHEN CURSOR_EQUIPO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Nombre del equipo: ' || ENOMBRE);
        DBMS_OUTPUT.PUT_LINE('Nombre del jugador: ' || JNOMBRE);
        DBMS_OUTPUT.PUT_LINE('Nacionalidad: ' || JNACIONALIDAD);
        DBMS_OUTPUT.PUT_LINE('Nickname: ' || JNICKNAME);
        DBMS_OUTPUT.PUT_LINE('Rol: ' || JROL);
        DBMS_OUTPUT.PUT_LINE('Nombre de la competicion: ' || CNOMBRE);
        DBMS_OUTPUT.PUT_LINE('-----------------------');
END LOOP;
END;
/
/*Para poder probarlo*/
EXECUTE INFO_GENERAL('Team Delta')
