/* Script para probar Funcionalidada de los Triggers */

/* Prueba Trigger 6 Jugadores Max por Equipo */
SELECT * FROM JUGADORES WHERE COD_EQUIPO = 1;

INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Oscar Cañellas', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Mixwell', 
                            'MID', 2000, 1);
                            
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Zahir Rivera', 'Peru', 
                            TO_DATE('28/07/2005', 'DD/MM/YYYY'), 'Za', 
                            'SUPPORT', 1000, 1);

SELECT * FROM JUGADORES WHERE COD_EQUIPO = 1;

ROLLBACK;



/* Prueba Trigger 2 Jugadores Minimo por Equipo */
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 21 Trig',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 21 TRIG';
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Juan Marquina', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Juanmi', 
                            'MID', 2000, (SELECT COD_EQUIPO 
                            FROM EQUIPOS 
                            WHERE UPPER(NOMBRE) = 'TEAM TEST 21 TRIG'));
                                        
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 22 Trig',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 22 TRIG';

INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Alonso Codere', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Alocod', 
                            'MID', 2000, (SELECT COD_EQUIPO 
                                          FROM EQUIPOS 
                                    WHERE UPPER(NOMBRE) = 'TEAM TEST 22 TRIG'));

INSERT INTO JUEGOS (NOMBRE, DESARROLLADORA, FECHA_LANZAMIENTO)
VALUES ('TEST TRIG 1', 'ADRIAN', '21/11/2023');

SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TRIG 1';

INSERT INTO COMPETICIONES 
(NOMBRE, FECHA_INICIO, FECHA_FIN, CURSO, EQUIPO_GANADOR, COD_JUEGO)
VALUES ('TEST TRIG', '26/04/2024', '27/04/2024', 0, NULL, 
(SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TRIG 1'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) VALUES (21,22);
                                        
ROLLBACK;



/* Prueba Trigger Numero de Equipos Par */
INSERT INTO JUEGOS (NOMBRE, DESARROLLADORA, FECHA_LANZAMIENTO)
VALUES ('TEST TEAM PAR TRIG JUEGO', 'ADRIAN', '21/11/2021');

SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO';

INSERT INTO COMPETICIONES
(NOMBRE, FECHA_INICIO, FECHA_FIN, CURSO, EQUIPO_GANADOR, COD_JUEGO)
VALUES ('TEST TEAM PAR TRIG', '02/05/2024', '03/05/2024', 0, NULL, 
(SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO')
);

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 31 Trig',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 31 TRIG';
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Charles Lukia', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Charli', 
                            'MID', 2000, 
(SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO')
);
                                        
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('TEAM TEST 32 TRIG',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 32 TRIG';

INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Za RetaBet', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'ZaBet', 
                            'MID', 2000, 
(SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO')
);
                            
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('TEAM TEST 33 TRIG',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 33 TRIG';
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Bai Codere', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Charli', 
                            'MID', 2000, 1);
                            
INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) 
VALUES ((SELECT COD_EQUIPO FROM EQUIPOS 
        WHERE UPPER(NOMBRE) = 'TEAM TEST 31 TRIG'), (SELECT COD_COMPE
                                                    FROM COMPETICIONES 
                                   WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG'));
                                   
INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) 
VALUES ((SELECT COD_EQUIPO FROM EQUIPOS 
        WHERE UPPER(NOMBRE) = 'TEAM TEST 32 TRIG'), (SELECT COD_COMPE
                                                    FROM COMPETICIONES 
                                   WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG'));
                                   
INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) 
VALUES ((SELECT COD_EQUIPO FROM EQUIPOS 
        WHERE UPPER(NOMBRE) = 'TEAM TEST 33 TRIG'), (SELECT COD_COMPE
                                                    FROM COMPETICIONES 
                                   WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG'));
                                   
        -- NO DEBERIA DEJAR CERRAR PLAZO INSCRIPCION
UPDATE COMPETICIONES
SET CURSO = 1
WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG';

SELECT *
FROM COMPETICIONES
WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG';

        -- SI INSERTAMOS UN CUARTO EQUIPO SI DEJA

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('TEAM TEST 34 TRIG',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 34 TRIG';
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('TEST FINAL', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'ADRIAN FINAL', 
                            'MID', 2000, (SELECT COD_EQUIPO 
                                        FROM EQUIPOS 
                                    WHERE UPPER(NOMBRE) = 'TEAM TEST 34 TRIG'));
                            
INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) 
VALUES ((SELECT COD_EQUIPO FROM EQUIPOS
        WHERE UPPER(NOMBRE) = 'TEAM TEST 34 TRIG'), (SELECT COD_COMPE
                                                    FROM COMPETICIONES 
                                   WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG'));

ROLLBACK;



/* Prueba Trigger Limite  Salario 200.000 */
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 40 Trig',
                                        TO_DATE('20/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG';

INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Jordi Fernandez', 'España', 
                            TO_DATE('11/11/1995', 'DD/MM/YYYY'), 'JRD', 
                            'MID', 8330, (SELECT COD_EQUIPO 
                            FROM EQUIPOS 
                            WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG'));
                            
INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO) 
VALUES ('Paco','Entrenador',8330,(SELECT COD_EQUIPO 
                            FROM EQUIPOS 
                            WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG'));

SELECT 'Jugador' AS TIPO,
       J.NOMBRE_JUGADOR AS NOMBRE,
       J.SUELDO AS SUELDO
FROM JUGADORES J
WHERE J.COD_EQUIPO = (SELECT COD_EQUIPO FROM EQUIPOS 
                      WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG')
UNION ALL
SELECT 'Staff' AS TIPO,
       S.NOMBRE AS NOMBRE,
       S.SUELDO AS SUELDO
FROM STAFF S
WHERE S.COD_EQUIPO = (SELECT COD_EQUIPO FROM EQUIPOS 
                      WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG');

INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Eduardo Segura', 'España', 
                            TO_DATE('07/07/1995', 'DD/MM/YYYY'), 'DSGR', 
                            'TOP', 8330, (SELECT COD_EQUIPO 
                            FROM EQUIPOS 
                            WHERE UPPER(NOMBRE) = 'TEAM TEST 40 TRIG'));
                            
                            
                            
/* Prueba Trigger minimo un entrenador */
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('TTT',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO)
VALUES ('John Run', 'Asistente', 2000, (SELECT COD_EQUIPO FROM EQUIPOS 
WHERE UPPER(NOMBRE) = 'TTT'));
                        
                        
                        
/* Prueba Trigger maximo un asistente */
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E4',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO)
VALUES ('Paco Jemez', 'Entrenador', 2000, (SELECT COD_EQUIPO FROM EQUIPOS 
WHERE UPPER(NOMBRE) = 'E4'));

INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO)
VALUES ('Jorge Minova', 'Asistente', 2000, (SELECT COD_EQUIPO FROM EQUIPOS 
WHERE UPPER(NOMBRE) = 'E4'));

INSERT INTO STAFF (NOMBRE,CARGO,SUELDO,COD_EQUIPO)
VALUES ('Alfred Stutgard', 'Asistente', 2000, (SELECT COD_EQUIPO FROM EQUIPOS 
WHERE UPPER(NOMBRE) = 'E4'));



/* Prueba Trigger Bloqueo Tabla Equipos Durante Competicion En Curso */
INSERT INTO JUEGOS (NOMBRE, DESARROLLADORA, FECHA_LANZAMIENTO)
VALUES ('TEST TEAM PAR TRIG JUEGO 2', 'ADRIAN', '21/11/2021');

SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO 2';

INSERT INTO COMPETICIONES
(NOMBRE, FECHA_INICIO, FECHA_FIN, CURSO, EQUIPO_GANADOR, COD_JUEGO)
VALUES ('TEST TEAM PAR TRIG C5', '02/05/2024', '03/05/2024', 0, NULL, 
(SELECT COD_JUEGO 
FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO 2'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 41 Trig',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'TEAM TEST 41 TRIG';
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Zapa Test', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'ZaPa Test', 
                            'MID', 2000, (SELECT COD_EQUIPO 
                                        FROM EQUIPOS 
                                    WHERE UPPER(NOMBRE) = 'TEAM TEST 41 TRIG'));  

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO, COD_COMPETICION) 
VALUES ((SELECT COD_EQUIPO FROM EQUIPOS 
        WHERE UPPER(NOMBRE) = 'TEAM TEST 41 TRIG'), (SELECT COD_COMPE
                                                    FROM COMPETICIONES 
                                WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG C5'));
                                   
UPDATE COMPETICIONES
SET CURSO = 1
WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG C5';

SELECT *
FROM COMPETICIONES
WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG C5';

ROLLBACK;
        -- Prueba para Insert (Datos Nuevos)
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('Team Test 42 Trig C5',
                                        TO_DATE('12/06/2011', 'DD/MM/YYYY'));
                                        
INSERT INTO JUGADORES (NOMBRE_JUGADOR, NACIONALIDAD, FECHA_NAC, NICKNAME, ROL,
SUELDO, COD_EQUIPO) VALUES ('Zapa Test 2', 'España', 
                            TO_DATE('10/10/1995', 'DD/MM/YYYY'), 'Zapa Test 2', 
                            'MID', 2000, 
(SELECT COD_JUEGO 
FROM JUEGOS WHERE UPPER(NOMBRE) = 'TEST TEAM PAR TRIG JUEGO 2'));

        -- Prueba para Update (Prueba con datos creados antes de cambiar el 
        -- estado de la competicion para probar UPDATE)
UPDATE EQUIPOS
SET FECHA_FUNDACION =  TO_DATE('15/07/2012', 'DD/MM/YYYY')
WHERE UPPER(NOMBRE) = 'Team Test 41 Trig';

UPDATE JUGADORES
SET NICKNAME = 'ZAPA TETS MAYUS'
WHERE UPPER(NICKNAME) = 'ZaPa Test';
        -- Prueba para Delete (Prueba con datos creados antes de cambiar el 
        -- estado de la competicion para probar DELETE)
DELETE FROM EQUIPOS WHERE UPPER(NOMBRE) = 'Team Test 41 Trig';
DELETE FROM JUGADORES WHERE UPPER(NICKNAME) = 'ZaPa Test';
        
        
        
/* Prueba Trigger enfrentamientos en mismo dia */
INSERT INTO JUEGOS (NOMBRE, DESARROLLADORA, FECHA_LANZAMIENTO) 
VALUES ('Maneater','Ubisoft','10/10/2010');

INSERT INTO COMPETICIONES 
(NOMBRE,FECHA_INICIO,FECHA_FIN,CURSO,EQUIPO_GANADOR,COD_JUEGO)
VALUES('TORNEO 11','25/04/2020','25/05/2020',0,NULL,(
SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'MANEATER'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E10',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));
                                    
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E11',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E12',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E13',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E10'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 11'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E11'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 11'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E12'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 11'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E13'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 11'));

INSERT INTO JORNADAS (NUM_JORNADA,DIA,COD_COMPE)
VALUES (1, TO_DATE('02/05/2024', 'DD/MM/YYYY'), (
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 11'));

INSERT INTO ENFRENTAMIENTOS (FECHA,COD_JORNADA,HORA,RESULTADO, 
                            COD_EQUIPO_LOCAL,COD_EQUIPO_VISITANTE)
VALUES (TO_DATE('02/05/2024', 'DD/MM/YYYY'), (
SELECT COD_JORNADAS FROM JORNADAS WHERE NUM_JORNADA = 1), '20:00', NULL, (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E10'), (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E11'));

INSERT INTO ENFRENTAMIENTOS (FECHA,COD_JORNADA,HORA,RESULTADO, 
                            COD_EQUIPO_LOCAL,COD_EQUIPO_VISITANTE)
VALUES (TO_DATE('03/05/2024', 'DD/MM/YYYY'), (
SELECT COD_JORNADAS FROM JORNADAS WHERE NUM_JORNADA = 1), '21:00', NULL, (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E10'), (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E11'));



/* EQUIPOS SIN REPETIR EN ENFRENTAMIENTOS */
INSERT INTO JUEGOS (NOMBRE, DESARROLLADORA, FECHA_LANZAMIENTO) 
VALUES ('F1','EA SPORTS','10/10/2010');

INSERT INTO COMPETICIONES 
(NOMBRE,FECHA_INICIO,FECHA_FIN,CURSO,EQUIPO_GANADOR,COD_JUEGO)
VALUES('TORNEO 10','25/04/2020','25/05/2020',0,NULL,(
SELECT COD_JUEGO FROM JUEGOS WHERE UPPER(NOMBRE) = 'F1'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E1',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));
                                    
INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E2',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO EQUIPOS (NOMBRE, FECHA_FUNDACION) VALUES ('E3',
TO_DATE('20/06/2011', 'DD/MM/YYYY'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E1'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 10'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E2'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 10'));

INSERT INTO EQUIPO_COMPETICION (COD_EQUIPO,COD_COMPETICION)VALUES((
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = 'E3'),(
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 10'));

INSERT INTO JORNADAS (NUM_JORNADA,DIA,COD_COMPE)
VALUES (3, TO_DATE('02/05/2024', 'DD/MM/YYYY'), (
SELECT COD_COMPE FROM COMPETICIONES WHERE UPPER(NOMBRE) = 'TORNEO 10'));

INSERT INTO ENFRENTAMIENTOS (FECHA,COD_JORNADA,HORA,RESULTADO, 
                            COD_EQUIPO_LOCAL,COD_EQUIPO_VISITANTE)
VALUES (TO_DATE('02/05/2024', 'DD/MM/YYYY'), (
SELECT COD_JORNADAS FROM JORNADAS WHERE NUM_JORNADA = 3), '20:00', NULL, (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E1'), (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E2'));

INSERT INTO ENFRENTAMIENTOS (FECHA,COD_JORNADA,HORA,RESULTADO, 
                            COD_EQUIPO_LOCAL,COD_EQUIPO_VISITANTE)
VALUES (TO_DATE('02/05/2024', 'DD/MM/YYYY'), (
SELECT COD_JORNADAS FROM JORNADAS WHERE NUM_JORNADA = 3), '10:00', NULL, (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E1'), (
SELECT COD_EQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE)='E3'));



/* Prueba Trigger Cierre Plazo Inscripcion */
INSERT INTO COMPETICIONES 
(NOMBRE, FECHA_INICIO, FECHA_FIN, CURSO, EQUIPO_GANADOR, COD_JUEGO)
VALUES ('Competición Futura', TO_DATE('2024-06-01', 'YYYY-MM-DD'), 
TO_DATE('2024-06-02', 'YYYY-MM-DD'), 0, NULL, 1);

SELECT * FROM COMPETICIONES WHERE NOMBRE = 'Competición Futura';

INSERT INTO COMPETICIONES 
(NOMBRE, FECHA_INICIO, FECHA_FIN, CURSO, EQUIPO_GANADOR, COD_JUEGO)
VALUES ('Competición Pasada', TO_DATE('2024-04-30', 'YYYY-MM-DD'), 
TO_DATE('2024-05-01', 'YYYY-MM-DD'), 0, NULL, 1);

SELECT * FROM COMPETICIONES WHERE NOMBRE = 'Competición Pasada';

UPDATE COMPETICIONES
SET FECHA_INICIO = TO_DATE('2024-04-29', 'YYYY-MM-DD')
WHERE NOMBRE = 'Competición Futura';

SELECT * FROM COMPETICIONES WHERE NOMBRE = 'Competición Futura';

UPDATE COMPETICIONES
SET FECHA_INICIO = TO_DATE('2024-05-01', 'YYYY-MM-DD')
WHERE NOMBRE = 'Competición Pasada';

SELECT * FROM COMPETICIONES WHERE NOMBRE = 'Competición Pasada';

DELETE FROM COMPETICIONES WHERE NOMBRE = 'Competición Pasada';

SELECT * FROM COMPETICIONES WHERE NOMBRE = 'Competición Pasada';
